// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATzAO2oRxflvdd_SLpJlflUzAJoRWr0E4',
    appId: '1:75231049160:web:8136db446edfd55755fcfd',
    messagingSenderId: '75231049160',
    projectId: 'novatasks-df483',
    authDomain: 'novatasks-df483.firebaseapp.com',
    storageBucket: 'novatasks-df483.firebasestorage.app',
    measurementId: 'G-R0CS8JPS9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPrFuuWbe387QqbqiwqxB_iMRZhy9sDT0',
    appId: '1:75231049160:android:a954334b91c22b1855fcfd',
    messagingSenderId: '75231049160',
    projectId: 'novatasks-df483',
    storageBucket: 'novatasks-df483.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVP7Cw3GhZUt8V6mP9O9IRYDiamBGup6M',
    appId: '1:75231049160:ios:469389f4dce6937255fcfd',
    messagingSenderId: '75231049160',
    projectId: 'novatasks-df483',
    storageBucket: 'novatasks-df483.firebasestorage.app',
    iosBundleId: 'com.example.novaTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVP7Cw3GhZUt8V6mP9O9IRYDiamBGup6M',
    appId: '1:75231049160:ios:469389f4dce6937255fcfd',
    messagingSenderId: '75231049160',
    projectId: 'novatasks-df483',
    storageBucket: 'novatasks-df483.firebasestorage.app',
    iosBundleId: 'com.example.novaTasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATzAO2oRxflvdd_SLpJlflUzAJoRWr0E4',
    appId: '1:75231049160:web:97e1c3564cf4f67055fcfd',
    messagingSenderId: '75231049160',
    projectId: 'novatasks-df483',
    authDomain: 'novatasks-df483.firebaseapp.com',
    storageBucket: 'novatasks-df483.firebasestorage.app',
    measurementId: 'G-RVEEB8CLFX',
  );
}
